package io.github.hikingc.matrixsdk.api.events;

import io.github.hikingc.matrixsdk.api.identifiers.EventID;

/// Additional information about the event. Not all fields are guaranteed to be set.
///
/// @param age the time in milliseconds that has elapsed since the event was sent. Generated by the
///   local homeserver, and may be incorrect if the servers is out of sync. which can cause the age
///   to either be negative or greater than it actually is.
/// @param membership the room membership of the user making the request, at the time of the event.
///   More information in the specification.
/// @param prev_content the `content` of the previous state event that was replaced by this event.
///   This field is generated by the local homeserver, and is only returned if the event is a state
///   event, and the client has permission to see the previous event.
/// @param redactedBecause the event that redacted this event, if any.
/// @param replacesState the Event ID of the state event replaced by this event. This field is
///   generated by the local homeserver, and is only returned if the event is a state event. Unlike
///   `prev_content`, this field is included regardless of history visibility.
/// @param transactionId the client-supplied transaction ID, for example, provided via `PUT
///   /_matrix/client/v3 /rooms/{roomId}/send/{eventType}/{txnId}`, if the client being given the
///   event is the same one which sent it.
public record UnsignedData(
    Long age,
    String membership,
    EventContent prev_content,
    ClientEvent<?> redactedBecause,
    EventID replacesState,
    String transactionId) {}
