package io.github.hikingc.matrixsdk.api.events;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.hikingc.matrixsdk.api.identifiers.UserID;
import java.util.Map;
import org.jspecify.annotations.NullMarked;

/// @param displayName a name which can be displayed to represent the user instead of their
///   third-party identifier
/// @param signed a block of content which has been signed by the identity server, which homeservers
///   can use to verify the event. Clients should ignore this.
@NullMarked
public record ThirdPartyInvite(
    @JsonProperty(required = true) String displayName,
    @JsonProperty(required = true) SignedThirdPartyInvite signed) {

  /// @param mxid the user ID that has been bound to the third-party identifier.
  /// @param signatures the identity server signatures for this block. This is a map of identity
  ///   server name to signing key identifier to base64-encoded signature.
  /// @param token The token generated by the identity server at the `/store_invite` endpoint.
  ///
  ///   It matches the `state_key` of the corresponding `m.room.third_party_invite` event.
  /// @see <a href="https://spec.matrix.org/v1.19/appendices/#signing-json">documentation about
  ///   Signing JSON</a>
  /// @see <a
  ///   href="https://spec.matrix.org/v1.19/identity-service-api/#post_matrixidentityv2store-invite">Identity
  ///   Service API</a>
  public record SignedThirdPartyInvite(
      @JsonProperty(required = true) UserID mxid,
      @JsonProperty(required = true) Map<String, Map<String, String>> signatures,
      @JsonProperty(required = true) String token) {}
}
